# Generated by Django 3.1.12 on 2021-10-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('vacancy', models.CharField(max_length=30)),
                ('arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='arrival date')),
                ('cv', models.CharField(max_length=20)),
            ],
        ),
    ]
