# Generated by Django 3.1.12 on 2021-10-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Closed')], default=1),
        ),
    ]
