# Generated by Django 3.1.12 on 2021-12-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=64)),
                ('value', models.TextField(default='', max_length=64)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.vacancy')),
            ],
        ),
    ]
