# Generated by Django 3.1.12 on 2021-12-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_skills_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='exist',
            field=models.BooleanField(default=False),
        ),
    ]
