# Generated by Django 3.1.12 on 2021-12-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_skills_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.candidate'),
            preserve_default=False,
        ),
    ]
