# Generated by Django 3.1.12 on 2021-12-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_skills_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='value',
        ),
        migrations.CreateModel(
            name='Required_skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(default='', max_length=64)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='skills',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.required_skills'),
            preserve_default=False,
        ),
    ]
